// <auto-generated />
namespace IRServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class resulttable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(resulttable));
        
        string IMigrationMetadata.Id
        {
            get { return "201712191423447_resulttable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
