// <auto-generated />
namespace IRServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class twoTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(twoTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201712151623222_twoTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
