// <auto-generated />
namespace IRServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class resultFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(resultFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201802201223200_resultFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
